######################## default configuration ####################
baseURL = "https://pattysung1.github.io"
languageCode = "zh-tw"
title = "PattySung"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
URL = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/venobox/venobox.min.js"
[[params.plugins.js]]
URL = "plugins/search/fuse.min.js"
[[params.plugins.js]]
URL = "plugins/search/mark.js"
[[params.plugins.js]]
URL = "plugins/search/search.js"


############################## navigation ###############################
[menu]

# main menu
[[menu.main]]
name = "About"
URL = "about/"
weight = 1

[[menu.main]]
name = "Works"
URL = "works/"
weight = 2

[[menu.main]]
name = "Travel"
URL = "travel/"
weight = 3

[[menu.main]]
name = "Contact"
URL = "contact/"
weight = 4

# footer menu
[[menu.footer]]
name = "About"
URL = "about/"
weight = 1

[[menu.footer]]
name = "Works"
URL = "works/"
weight = 2

[[menu.footer]]
name = "Travel"
URL = "travel/"
weight = 3

[[menu.footer]]
name = "Contact"
URL = "contact/"
weight = 4


#################### default parameters ################################
[params]
logo = "images/shinylogo.png"
home = "Home"
# Meta data
description = "This is Patty Sung's website."
author = "PattySung"

# Contact Information
mobile = "a9870456321"
email = "sungpeihsuannccu@gmail.com"
location = "Taiwan"
# copyright
copyright = "| copyright &copy; 2023 [PattySung](https://pattysung1.github.io/) All Rights Reserved |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# search
[params.search]
enable = false

############################ news letter ########################
[params.newsletter]
enable = false
title = "Join Our Newsletter"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"


# cookies
[params.cookies]
enable = true
expire_days = 2


############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "#"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/shinybearfamily?s=21&t=TNehV3PHQsHhY05bzFJ-Jg"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/pooh.travel.blog?igshid=MjEwN2IyYWYwYw=="

[[params.social]]
title = "github"
icon = "ti-github" # themify icon : https://themify.me/themify-icons
link = "https://github.com/settings/profile"

[[params.social]]
title = "linkedin"
icon = "ti-linkedin" # themify icon : https://themify.me/themify-icons
link = "https://www.linkedin.com/in/pei-hsuan-sung-4b3599153/"

[markup]
  [markup.highlight]
    style = 'catppuccin-frappe'